#!/bin/sh

#
# $RCSfile: run_command,v $ $Revision: 1.2 $ $Date: 2004/03/17 19:24:51 $
#
# Command exec wrapper.  
#

# 
# This file is part of LinCS/tiger.  
# 
# LinCS/tiger is distributed under the terms of the GNU Lesser General Public
# License version 2 or any later version.  See the file COPYING.LIB for copying 
# permission or http://www.gnu.org. 
#                                                                            
# THIS MATERIAL IS PROVIDED AS IS, WITH ABSOLUTELY NO WARRANTY EXPRESSED OR  
# IMPLIED, without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE.  ANY USE IS AT YOUR OWN RISK. 
#                                                                            
# Permission to modify the code and to distribute modified code is granted, 
# provided the above notices are retained, and a notice that the code was 
# modified is included with the above copyright notice. 
# 
 
#set -x


echo ""
echo "**** [$@] "

eval "$@"
if test $? -eq 0 ; then
    echo "**** [$@] success"
else
    $TSTDIR/print_red "**** [$@] FAILED"
fi

exit $?
