#!/bin/sh

#
# Build web site and doxygen/html templates.
# Usage: ./makesite.sh
# Keep in sync with cleanup.sh
#

echo "Building site..."

cp ../doxygen.css .
cp ../doxygen.css ../architecture


when=`date`

files1=`ls *.body`
files2=`ls ../architecture/*.body`

# files to work on
files="$files1 $files2"
# resulting files
nfiles=`echo $files | sed s/.body/.html/g`
TEMPF=tempf

for f in $files
do
    nf=`echo $f | sed s/.body/.html/`
    echo "    Building    $nf"
    #
    echo "<!-- Automatically generated by $0 from $f on $when -->" > $nf
    cat header.dot >> $nf
    cat menu.dot   >> $nf
    cat body_sep1.dot   >> $nf
    cat $f         >> $nf
    cat body_sep1.dot   >> $nf
    cat menu.dot   >> $nf
    cat footer.dot >> $nf
    
    ## global index.html 
    #if test $nf = "index.html"; then
    #    # change img tag and menu links 
    #    CMD="perl -e ""'""while(<>) {s:../site/:site/:g; print;}""'"" <$nf >$TEMPF" 
    #    eval $CMD
    #    mv $TEMPF "x"$nf
    #    mv "x"$nf ../$nf
    #fi
    
done

echo "Site building done: $nf."




DOXY_H=doxygen.header
DOXY_F=doxygen.footer

cat header.dot      >  $DOXY_H
cat menu.dot        >> $DOXY_H
echo "<tr> <td colspan=\"2\" width=\"100%\">" >> $DOXY_H
echo "<br><address style=\"align: right;\">" >> $DOXY_H
echo "<small>Generated by <a href=\"http://www.doxygen.org/index.html\">" >> $DOXY_H
echo "<img src=\"doxygen.png\" alt=\"doxygen\" align=\"middle\" border=0 width=110 height=53>" >> $DOXY_H
echo "</a> </small></address>" >> $DOXY_H
echo "</td></tr>" >> $DOXY_H
cat body_sep1.dot   >> $DOXY_H

cat body_sep2.dot   >  $DOXY_F
cat menu.dot        >> $DOXY_F
cat footer.dot      >> $DOXY_F
echo "Done with $DOXY_H/$DOXY_F."



HTML_DOT=html_dot.html
cat $DOXY_H        >  $HTML_DOT
echo ""            >> $HTML_DOT
echo " some text"  >> $HTML_DOT
echo ""            >> $HTML_DOT
cat $DOXY_F        >> $HTML_DOT
echo "Done $HTML_DOT."


